spring.application.name=project
# src/main/resources/application.properties
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.datasource.url=jdbc:mysql://20.239.232.148:3306/long4nihongo?user=hoanghailonguyno
spring.datasource.username=hoanghailonguyno
spring.datasource.password=HLong20102004@
server.port=8080
logging.level.org.springframework=DEBUG

spring.data.mongodb.uri=mongodb+srv://hoanghailonguyno:1TOdjLkyilqZ4dx0@cluster0.yjs3o.mongodb.net/long4nihongo?retryWrites=true&w=majority&appName=Cluster0
# The below line to turnoff connection to database so the @Repository cannot be initialized as bean // remember to removed
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.oauth2.client.registration.google.client-id=443548651961-4plm7ruac53b5tfnif6q07b3jmcq83q8.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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
#In google cloud, the uri must be : http://....../login/oauth2/code/google


spring.security.oauth2.client.registration.facebook.client-id=972235024664977
spring.security.oauth2.client.registration.facebook.client-secret=9a058784916ec04e2e71f8cbd86f1d55
